Trademusic.Web/Areas/Admin/Models/Instrument/InstrumentCreateViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

using Trademusic.Web.App_GlobalResources;

namespace Trademusic.Web.Areas.Admin.Models.Instrument
{
    public class InstrumentCreateViewModel
    {
        [Display(ResourceType = typeof(Language), Name = "ADDRESS")]
        public CORE.Domain.Classes.Instrument Instrument { get; set; }

        [Display(ResourceType = typeof(Language), Name = "Family")]
        public List<SelectListItem> Family { get; set; }

        [Display(ResourceType = typeof(Language), Name = "IMAGE")]
        public List<HttpPostedFileBase> Images { get; set; }

        [Display(ResourceType = typeof(Language), Name = "IMAGES")]
        public List<string> ImagesFiles { get; set; }
    }
}

Trademusic.Web/Areas/Admin/Models/Instrument/InstrumentIndexViewModel.cs
using System.ComponentModel.DataAnnotations;

using Trademusic.Web.App_GlobalResources;

namespace Trademusic.Web.Areas.Admin.Models.Instrument
{

    /// <summary>
    /// ViewModel para mostrar el listado del instrumento de administración
    /// </summary>
    public class InstrumentIndexViewModel
    {
        public int Id { get; set; }
      
        [Display(ResourceType = typeof(Language), Name = "BRAND")]
        public string Brand { get; set; }

        [Display(ResourceType = typeof(Language), Name = "MODEL")]
        public string Model { get; set; }

        [Display(ResourceType = typeof(Language), Name = "PRICE")]
        [DisplayFormat(DataFormatString = "{0:0,00}", ApplyFormatInEditMode = true)]
        public decimal Price { get; set; }

        [Display(ResourceType = typeof(Language), Name = "USER")]
        public string User { get; set; }
    }
}

Trademusic.Web/Areas/Admin/Controllers/InstrumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Trademusic.CORE.Contracts;
using Trademusic.Web.Areas.Admin.Models.Instrument;
using Trademusic.Web.JQueryDataTable;

namespace Trademusic.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// Controlador de los instrumentos - Solo accesible con el rol Admin
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class InstrumentController : Controller
    {
        private IInstrumentManager instrumentManager;
        private IFamilyManager familyManager;
        private IUserManager userManager;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="instrumentManager"></param>
        /// <param name="familyManager"></param>
        public InstrumentController(IInstrumentManager instrumentManager, IFamilyManager familyManager, IUserManager userManager)
        {
            this.instrumentManager = instrumentManager;
            this.familyManager = familyManager;
            this.userManager = userManager;
        }

        /// <summary>
        /// Método que devuelve todos los instrumentos en formato JSon para pintar una tabla con Ajax
        /// </summary>
        /// <returns></returns>
        public ActionResult IndexData()
        {
            JQueryDataTableRequest request = new JQueryDataTableRequest(System.Web.HttpContext.Current.Request);
            var model =
                instrumentManager.GetAll("Family")
                    .Select(e => new InstrumentIndexViewModel {
                                Id = e.Id,
                                Brand = e.Brand,
                                Model = e.Model,
                                Price = e.Price,
                                User = e.User.Email
                            });

            JQueryDataTableResponse result = JQueryHelper.CreateJQueryDataTableResponse(model, request);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Método que muestra una tabla con todos los instrumentos
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var model =
                instrumentManager.GetAll("Family")
                    .Select(e => new InstrumentIndexViewModel {
                        Id = e.Id,
                        Brand = e.Brand,
                        Model = e.Model,
                        Price = e.Price,
                        User = e.User.Email
                    });

            return View(model);
        }

        /// <summary>
        /// Método que pinta la vista de edición de un instrumento
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            InstrumentCreateViewModel model = new InstrumentCreateViewModel();
            model = PrepareViewModel(model);
            model.Instrument = instrumentManager.GetById(id);
            model.Instrument.User = userManager.GetById(model.Instrument.UserId);
            model.ImagesFiles = new List<string>();

            var referenceUri = new Uri(@Server.MapPath("~\\Images\\Instrument\\"));

            foreach (var file in Directory.GetFiles(@Server.MapPath("~\\Images\\Instruments\\"), id + "_*"))
            {
                var fileUri = new Uri(file);
                model.ImagesFiles.Add("/Images/Instrument/" + referenceUri.MakeRelativeUri(fileUri));
            }
            return View(model);       
        }

        /// <summary>
        /// Método de edición de un instrumento
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(int id, InstrumentCreateViewModel model)
        {
            var instrument = instrumentManager.GetById(id);
            model.Instrument.UserId = instrument.User.Id;
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Images != null)
                    {
                        foreach (var image in model.Images)
                        {
                            if (image != null)
                            {
                                image.SaveAs(Path.Combine(@Server.MapPath("~\\Images\\Instruments\\"), id + "_" + model.Images.IndexOf(image) + ".jpg"));
                            }
                        }
                    }
                
                    instrumentManager.Edit(id, model.Instrument);
                    instrumentManager.db.SaveChanges();
                    model = PrepareViewModel(model);
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch(Exception e)
            {
                model = PrepareViewModel(model);
                return View(model);
            }
        }

        /// <summary>
        /// Método que prepara los dropdownlist de la vista
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        private InstrumentCreateViewModel PrepareViewModel(InstrumentCreateViewModel model)
        {
            model.Family =
                familyManager.GetAll()
                    .Select(f => new SelectListItem { Value = f.Id.ToString(), Text = f.Name })
                    .ToList();
            return model;
        } 
    }
}

Trademusic.Web/Areas/Admin/Views/Instrument/Edit.cshtml
@model Trademusic.Web.Areas.Admin.Models.Instrument.InstrumentCreateViewModel

@{
    ViewBag.Title = Resources.Language.ADMINISTRATION;
}

<h2 class="adminTitle">Editar instrumento</h2>

@using (Html.BeginForm("Edit", "Instrument", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" id="formAdmin">
        @Html.HiddenFor(m => m.Instrument.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Usuario", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instrument.User.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Instrument.User.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Marca", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instrument.Brand, new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.Instrument.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Modelo", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instrument.Model, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Instrument.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Precio", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instrument.Price, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Instrument.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Fecha", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instrument.DateTime, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Instrument.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Descripción", new { @class = "control-label col-md-3" })
            <div class="col-md-7">
                @Html.TextAreaFor(model => model.Instrument.Description, new { @class = "txtAreaAdmin form-control"})
                @Html.ValidationMessageFor(model => model.Instrument.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Familia", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Instrument.FamilyId, Model.Family, new { @class = "ddlAdmin form-control" })
                @Html.ValidationMessageFor(model => model.Instrument.FamilyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Imagen", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Images, null, new { type = "file", @class = "input-file", @multiple = true })
                @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-top: 30px;">
            @foreach (var image in Model.ImagesFiles)
                {
                <img src="@image" style="width: 100px; max-height: 100px" />
            }
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-primary" id="btnAdmin" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index", "", new { @class = "btnVolver" })
</div>

Trademusic.Web/Areas/Admin/Views/Instrument/Index.cshtml
@model IEnumerable<Trademusic.Web.Areas.Admin.Models.Instrument.InstrumentIndexViewModel>
@{
    ViewBag.Title = Resources.Language.ADMINISTRATION;
}

<h2 class="adminTitle">Listado de instrumentos</h2>
<div class="row">
    <table id="DataTable" class="display col-sm-12" cellspacing="0">
        <thead>
            <tr>
                <th></th>
                <th>
                    Marca
                </th>
                <th>
                    Modelo
                </th>
                <th>
                    Precio
                </th>
                <th>
                    Usuario
                </th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@section Scripts
{
    <script type="text/javascript">
    $(document).ready(function () {
        var table = $('#DataTable').DataTable({
            "bProcessing": true,
            "bServerSide": true,
            "oLanguage": { "sUrl": "//cdn.datatables.net/plug-ins/1.10.7/i18n/Spanish.json" },
            "columnDefs": [
            {
                "render": function (data, type, row) {
                    return "<a data-id='" + data + "' href='@Url.Action("Edit")/" + data + "@(Request.QueryString.Count!=0 ? "?" + Request.QueryString : "")" + "' class='btn btn-pink'>Editar</a>";
                    },
                    width: "1%",
                    "targets": 0
                }],
                "sAjaxSource": "@Url.Action("IndexData")",
                "fnServerData": function (sSource, aoData, fnCallback) {
                    $.ajax({
                        "dataType": 'json',
                        "contentType": "application/json; charset=utf-8",
                        "type": "GET",
                        "url": sSource,
                        "data": aoData,
                        "success": function (msg) {
                            fnCallback(msg);
                            $("#DataTable").show();
                        },
                        error: function (xhr, textStatus, error) {
                            if (typeof console == "object") {
                                console.log(xhr.status + "," + xhr.responseText + "," + textStatus + "," + error);
                            }
                        }
                    });
                }
            });
        });
    </script>
}