Trademusic.Web/Models/App/InstrumentListViewModel.cs
using System;
using Trademusic.CORE.Domain.Classes;

namespace Trademusic.Web.Models.App
{
    public class InstrumentListViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Brand { get; set; }

        public decimal Price { get; set; }

        public string Description { get; set; }

        public DateTime DateTime { get; set; }

        public ApplicationUser User { get; set; }

        public string Family { get; set; }

        public string EngFamily { get; set; }

        public string Image
        {
            get
            {
                return "/Images/Instruments/" + BuildNameImage(Id);
            }
            private set { }
        }

        private string BuildNameImage(int varietyId)
        {
            return $"{varietyId}_0.jpg";
        }
    }
}

Trademusic.Web/Models/UserSection/FavoritesRemoveViewModel.cs
namespace Trademusic.Web.Models.UserSection
{
    public class FavoritesRemoveViewModel
    {
        public int DeleteId { get; set; }
    }
}

Trademusic.Web/Models/UserSection/FavoritesViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Trademusic.CORE.Domain.Classes;

namespace Trademusic.Web.Models.UserSection
{
    public class FavoritesViewModel
    {
        public int Id { get; set; }

        public string Brand { get; set; }

        public string Model { get; set; }

        public DateTime Date { get; set; }

        [DisplayFormat(DataFormatString = "{0:0,00}", ApplyFormatInEditMode = true)]
        public decimal Price { get; set; }

        public ApplicationUser User { get; set; }

        public string City { get; set; }

        public bool IsSold { get; set; }

        public int FavoriteId { get; set; }

        public Favorite Favorite { get; set; }

        public string ImageFile { get; set; }

        public string Image
        {
            get
            {
                return "/Images/Instruments/" + BuildNameImage(Id);
            }
            private set { }
        }

        private string BuildNameImage(int varietyId)
        {
            return $"{varietyId}_0.jpg";
        }
    }
}

Trademusic.Web/Models/UserSection/InstrumentCreateViewModel.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Trademusic.CORE.Domain.Classes;

namespace Trademusic.Web.Models.UserSection
{
    public class InstrumentCreateViewModel
    {
        public Instrument Instrument { get; set; }

        public List<SelectListItem> Families { get; set; }

        public List<HttpPostedFileBase> Images { get; set; }

        public List<string> ImagesFiles { get; set; }

        public string ImageFile { get; set; }

        public ApplicationUser User { get; set; }
    }
}

Trademusic.Web/Models/UserSection/InstrumentIndexViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Trademusic.Web.Models.UserSection
{
    public class InstrumentIndexViewModel
    {
        public int Id { get; set; }

        public string Brand { get; set; }

        public string Model { get; set; }

        [DisplayFormat(DataFormatString = "{0:0,00}", ApplyFormatInEditMode = true)]
        public decimal Price { get; set; }

        public string User { get; set; }

        public string ImageFile { get; set; }

        public string Image
        {
            get
            {
                return "/Images/Instruments/" + BuildNameImage(Id);
            }
            private set { }
        }

        private string BuildNameImage(int varietyId)
        {
            return $"{varietyId}_0.jpg";
        }
    }
}

Trademusic.Web/Models/UserSection/InstrumentRemoveViewModel.cs
namespace Trademusic.Web.Models.UserSection
{
    public class InstrumentRemoveViewModel
    {
        public int DeleteId { get; set; }
    }
}

Trademusic.Web/Models/UserSection/MainViewModel.cs
using System.Web;
using Trademusic.CORE.Domain.Classes;

namespace Trademusic.Web.Models.UserSection
{
    public class MainViewModel
    {
        public ApplicationUser User { get; set; }

        public string UserId { get; set; }

        public HttpPostedFileBase Image { get; set; }

        public string ImageFile { get; set; }

        public bool Favoritos { get; set; }

        public bool Instrumentos { get; set; }

        public bool Mensajes { get; set; }
    }
}

Trademusic.Web/Models/UserSection/MessageRemoveViewModel.cs
namespace Trademusic.Web.Models.UserSection
{
    public class MessageRemoveViewModel
    {
        public int MessagesCount { get; set; }
        public int DeleteId { get; set; }
    }
}

Trademusic.Web/Models/UserSection/MessageViewModel.cs
using System;
using Trademusic.CORE.Domain.Classes;

namespace Trademusic.Web.Models.UserSection
{
    public class MessageViewModel
    {
        public int Id { get; set; }

        public string User { get; set; }

        public string UserId { get; set; }

        public string Text { get; set; }

        public DateTime Date { get; set; }

        public string Owner { get; set; }

        public Message Message { get; set; }

        public Instrument Instrument { get; set; }

        public string UserImage
        {
            get
            {
                return "/Images/Users/" + BuildNameImageUser(UserId);
            }
            private set { }
        }

        private string BuildNameImageUser(string userId)
        {
            return $"{userId}.jpg";
        }

        public string OwnerImage
        {
            get
            {
                return "/Images/Users/" + BuildNameImageOwner(Owner);
            }
            private set { }
        }

        private string BuildNameImageOwner(string ownerId)
        {
            return $"{ownerId}.jpg";
        }

        public string ImageFile { get; set; }
    }
}

Trademusic.Web/Models/UserSection/UserCreateViewModel.cs
using System.Web;
using Trademusic.CORE.Domain.Classes;

namespace Trademusic.Web.Models.UserSection
{
    public class UserCreateViewModel
    {
        public ApplicationUser User { get; set; }

        public HttpPostedFileBase Image { get; set; }

        public string ImageFile { get; set; }
    }
}

Trademusic.Web/Controllers/UserSectionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Trademusic.CORE.Contracts;
using Trademusic.CORE.Domain.Classes;
using Trademusic.Web.JQueryDataTable;
using Trademusic.Web.Models.UserSection;
using System.Web;
using Trademusic.Web.App_GlobalResources;
using System.Globalization;

namespace Trademusic.Web.Controllers
{
    [Authorize]
    public class UserSectionController : Controller
    {
        private IInstrumentManager instrumentManager;
        private IFamilyManager familyManager;
        private IUserManager userManager;
        private IFavoriteManager favoriteManager;
        private IMessageManager messageManager;
        private string _userId = String.Empty;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="instrumentManager"></param>
        /// <param name="familyManager"></param>
        /// <param name="userManager"></param>
        /// <param name="favoriteManager"></param>
        /// <param name="messageManager"></param>
        public UserSectionController(IInstrumentManager instrumentManager, IFamilyManager familyManager, IUserManager userManager, IFavoriteManager favoriteManager, IMessageManager messageManager)
        {
            this.instrumentManager = instrumentManager;
            this.familyManager = familyManager;
            this.userManager = userManager;
            this.favoriteManager = favoriteManager;
            this.messageManager = messageManager;
        }

        /// <summary>
        /// Método que pinta la pantalla principal de la sección de usuario
        /// </summary>
        /// <returns></returns>
        public ActionResult Main()
        {
            MainViewModel model = new MainViewModel();
            model.UserId = User.Identity.GetUserId();
            model.User = userManager.GetById(model.UserId);

            //ViewBags para la validación por JQuery de los botones: Listado de instrumentos, Favoritos y Mensajes
            ViewBag.messages = messageManager.GetAllByOwnerId(model.UserId).Count();
            ViewBag.instruments = instrumentManager.GetAllByUserId(model.UserId).Count();
            ViewBag.favorites = favoriteManager.GetAllByUserId(model.UserId).Count();

            UserData();

            return View(model);
        }

        /// <summary>
        /// Método que devuelve todos los instrumentos en formato JSon para pintar una tabla con Ajax
        /// </summary>
        /// <returns></returns>
        public ActionResult InstrumentList()
        {
            _userId = User.Identity.GetUserId();
            UserData();

            var model =
                instrumentManager.GetAllByUserId(_userId)
                    .Select(e => new FavoritesViewModel {
                        Id = e.Id,
                        Brand = e.Brand,
                        Model = e.Model,
                        Price = e.Price,
                        Date = e.DateTime,
                        User = e.User
                    });

            return View(model);
        }

        /// <summary>
        /// Método que pinta la vista de creación de un instrumento
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateInstrument()
        {
            UserData();

            InstrumentCreateViewModel model = new InstrumentCreateViewModel();
            model = PrepareViewModel(model);

            return View(model);
        }

        /// <summary>
        /// Método que crea un instrumento
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateInstrument(InstrumentCreateViewModel model)
        {
            UserData();
            try
            {
                if (ModelState.IsValid)
                {
                    model.Instrument.UserId = User.Identity.GetUserId();
                    model.Instrument.DateTime = DateTime.Today;
                    instrumentManager.Add(model.Instrument);
                    instrumentManager.db.SaveChanges();

                    if (model.Images != null)
                    {
                        foreach (var image in model.Images)
                        {
                            image.SaveAs(
                                Path.Combine(
                                    @Server.MapPath("~\\Images\\Instruments\\"),
                                    model.Instrument.Id + "_" + model.Images.IndexOf(image) + ".jpg"));
                        }
                    }
                    instrumentManager.Edit(model.Instrument.Id, model.Instrument);
                    instrumentManager.db.SaveChanges();
                    return RedirectToAction("Main");
                }
                model = PrepareViewModel(model);
                return View(model);
            }
            catch (Exception e)
            {
                return View("Error" + e);
            }
        }

        /// <summary>
        /// Método que pinta la vista de edición de un instrumento
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditInstrument(int id)
        {
            InstrumentCreateViewModel model = new InstrumentCreateViewModel();
            model = PrepareViewModel(model);
            model.Instrument = instrumentManager.GetById(id);
            model.ImagesFiles = new List<string>();
            UserData();

            var referenceUri = new Uri(@Server.MapPath("~\\Images\\Instruments\\"));

            foreach (var file in Directory.GetFiles(@Server.MapPath("~\\Images\\Instruments\\"), id + "_*"))
            {
                var fileUri = new Uri(file);
                model.ImagesFiles.Add("/Images/Instruments/" + referenceUri.MakeRelativeUri(fileUri));
            }
            return View(model);
        }

        /// <summary>
        /// Método de edición de un instrumento
        /// </summary>
        /// <param name="id"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditInstrument(int id, InstrumentCreateViewModel model)
        {
            var instrument = instrumentManager.GetById(id);
            model.Instrument.UserId = instrument.User.Id;
            model.Instrument.DateTime = instrument.DateTime;

            try
            {
                if (ModelState.IsValid)
                {
                    if (model.Images != null)
                    {
                        foreach (var image in model.Images)
                        {
                            if (image != null)
                            {
                                image.SaveAs(Path.Combine(@Server.MapPath("~\\Images\\Instruments\\"), id + "_" + model.Images.IndexOf(image) + ".jpg"));
                            }
                        }
                    }
                   
                    instrumentManager.Edit(id, model.Instrument);
                    instrumentManager.db.SaveChanges();
                    model = PrepareViewModel(model);
                    return RedirectToAction("InstrumentList");
                }
                return View(model);
            }
            catch (Exception e)
            {
                return View("Error" + e);
            }
        }

        /// <summary>
        /// Método que devuelve todos los favoritos en formato JSon para pintar una tabla con Ajax
        /// </summary>
        /// <returns></returns>
        public ActionResult Favorites()
        {
            var userId = User.Identity.GetUserId();
            UserData();
            var model =
                favoriteManager.GetAllByUserId(userId)
                    .Select(e => new FavoritesViewModel {
                        Id = e.Instrument.Id,
                        FavoriteId = e.Id,
                        Brand = e.Instrument.Brand,
                        Model = e.Instrument.Model,
                        Price = e.Instrument.Price,
                        User = e.User,
                        City = e.Instrument.User.City              
                    });

            return View(model);
        }

        /// <summary>
        /// Método que añade un favorito al listado de favoritos del usuario
        /// </summary>
        /// <returns></returns>
        public ActionResult AddToFavorites(int id)
        {
            var userId = User.Identity.GetUserId();
            var user = userManager.GetById(userId);
            var instrument = instrumentManager.GetById(id);

            try
            {
                Favorite model = new Favorite { Instrument = instrument, User = user };

                favoriteManager.Add(model);
                favoriteManager.db.SaveChanges();

                return RedirectToAction("Favorites");
            }
            catch (Exception e)
            {
                return View("Error" + e);
            }
        }

        /// <summary>
        /// Método que elimina por llamada Ajax un favorito
        /// </summary>
        /// <param name="favoriteId"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult RemoveFromFavorites(int favoriteId)
        {
            var favorite = favoriteManager.GetAll().Single(f => f.Id == favoriteId);

            if (favorite != null)
            {
                favoriteManager.Delete(favorite);
                favoriteManager.db.SaveChanges();
            }

            var results = new FavoritesRemoveViewModel
            {
                DeleteId = favoriteId
            };
            return Json(results);
        }

        /// <summary>
        /// Método que contiene los datos del usuario (Datos + Imagen) para la sección izquierda de las pantallas de la sección de usuario
        /// </summary>

Trademusic.Web/Views/UserSection/CreateInstrument.cshtml
@model Trademusic.Web.Models.UserSection.InstrumentCreateViewModel
@{
    ViewBag.Title = Resources.Language.INSTRUMENT;
}

<div class="container" id="mainContainer">
    <div class="row" id="seccionContenedorLista">
        <div class="col-sm-2" id="seccionFiltrosLeft">
            @{Html.RenderPartial("_LeftSideMenuUserSection");}
        </div>
        <div class="col-sm-10">
            <h2 class="titleUSListLeft">@Resources.Language.INSTRUMENT</h2>
            <legend class="recuadroLeft">
                @using (Html.BeginForm("CreateInstrument", "UserSection", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="formulario">
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.Label(Resources.Language.FAMILY, new { @class = "control-label col-md-3" })
                                <div class="col-md-7">
                                    @Html.DropDownListFor(model => model.Instrument.FamilyId, Model.Families, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Instrument.FamilyId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label(Resources.Language.BRAND, new { @class = "control-label col-md-3" })
                                <div class="col-md-7">
                                    @Html.EditorFor(model => model.Instrument.Brand, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Instrument.Brand, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label(Resources.Language.MODEL, new { @class = "control-label col-md-3" })
                                <div class="col-md-7">
                                    @Html.EditorFor(model => model.Instrument.Model, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Instrument.Model, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label(Resources.Language.PRICE, new { @class = "control-label col-md-3" })
                                <div class="col-md-7">
                                    @Html.EditorFor(model => model.Instrument.Price, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Instrument.Price, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label(Resources.Language.DESCRIPTION, new { @class = "control-label col-md-3" })
                                <div class="col-md-7">
                                    @Html.EditorFor(model => model.Instrument.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Instrument.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Imagen", new { @class = "control-label col-md-3" })
                                <div class="col-md-7">
                                    @Html.TextBoxFor(model => model.Images, null, new { type = "file", @class = "input-file", @multiple = true })
                                    @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })

                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="@Resources.Language.PUBLISH" class="btn btn-primary btn-xl page-scroll" id="btnEditar" />
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </legend>
        </div>
    </div>
</div>

Trademusic.Web/Views/UserSection/EditInstrument.cshtml
@model Trademusic.Web.Models.UserSection.InstrumentCreateViewModel
@{
    ViewBag.Title = Resources.Language.EDIT_INSTRUMENT;
}

<div class="container" id="mainContainer">
    <div class="row" id="seccionContenedorLista">
        <div class="col-sm-2" id="seccionFiltrosLeft">
            @{Html.RenderPartial("_LeftSideMenuUserSection");}
        </div>
        <div class="col-sm-10">
            <h2 class="titleUSListLeft">@Resources.Language.EDIT_INSTRUMENT</h2>
            <legend class="recuadroLeftEditInstrument">
                @using (Html.BeginForm("EditInstrument", "UserSection", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="formulario">
                        <hr />
                        @Html.HiddenFor(m => m.Instrument.Id)
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.Label(Resources.Language.BRAND, new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.Instrument.Brand, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Instrument.Brand, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.MODEL, new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.Instrument.Model, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Instrument.Model, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.PRICE, new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.Instrument.Price, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Instrument.Price, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.DESCRIPTION, new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.EditorFor(model => model.Instrument.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Instrument.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.FAMILY, new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.DropDownListFor(model => model.Instrument.FamilyId, Model.Families, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Instrument.FamilyId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.IMAGE, new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(model => model.Images, null, new { type = "file", @class = "input-file", @multiple = true })
                                @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group" style="margin-left: 115px; margin-top: 30px;">
                            @foreach (var image in Model.ImagesFiles)
                            {
                                <img src="@image" style="width: 100px; max-height: 100px" />
                            }
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="@Resources.Language.EDIT" class="btn btn-primary btn-xl page-scroll" id="btnEditar" />
                            </div>
                        </div>
                    </div> 
                }
            </legend>
        </div>
    </div>
</div>

Trademusic.Web/Views/UserSection/EditUser.cshtml
@model Trademusic.Web.Models.UserSection.UserCreateViewModel
@{
    ViewBag.Title = Resources.Language.EDIT_USER;
}

<div class="container" id="mainContainer">
    <div class="row" id="seccionContenedorLista">
        <div class="col-sm-2" id="seccionFiltrosLeft">
            @{Html.RenderPartial("_LeftSideMenuUserSection");}
        </div>
        <div class="col-sm-10">
            <h2 class="titleUSListLeft">@Resources.Language.EDIT_USER_INFO</h2>
            <legend class="recuadroLeft">
                @using (Html.BeginForm("EditUser", "UserSection", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="formulario">
                        @Html.ValidationSummary("", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.Label(Resources.Language.NAME, new { @class = "col-md-3 control-label" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.User.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.User.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.SURNAME1, new { @class = "col-md-3 control-label" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.User.SurName1, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.User.SurName1, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.SURNAME2, new { @class = "col-md-3 control-label" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.User.SurName2, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.User.SurName2, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.ADDRESS, new { @class = "col-md-3 control-label" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.User.Address, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.ZIPCODE, new { @class = "col-md-3 control-label" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.User.ZipCode, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.User.ZipCode, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.CITY, new { @class = "col-md-3 control-label" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.User.City, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.User.City, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.EMAIL, new { @class = "col-md-3 control-label" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(m => m.User.Email, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.User.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label(Resources.Language.IMAGE, new { @class = "control-label col-md-3" })
                            <div class="col-md-7">
                                @Html.TextBoxFor(model => model.Image, null, new { type = "file", @class = "input-file", @multiple = true })
                                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <img src="@Model.ImageFile" style="width: 100px" />
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="@Resources.Language.EDIT" class="btn btn-primary btn-xl page-scroll" id="btnEditar" />
                            </div>
                        </div>
                    </div>
                }
            </legend>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}