Trademusic.Web/Areas/Admin/Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Trademusic.CORE.Contracts;
using Trademusic.Web.Areas.Admin.Models.User;
using Trademusic.Web.JQueryDataTable;

namespace Trademusic.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// Controlador de los usuarios - Solo accesible con el rol Admin
    /// </summary>
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private IUserManager userManager;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="userManager"></param>
        public UserController(IUserManager userManager)
        {
            this.userManager = userManager;
        }

        /// <summary>
        /// Método que devuelve todos los usuarios en formato JSon para pintar una tabla con Ajax
        /// </summary>
        /// <returns></returns>
        public ActionResult IndexData()
        {
            JQueryDataTableRequest request = new JQueryDataTableRequest(System.Web.HttpContext.Current.Request);
            var model =
                userManager.GetAll()
                    .Select(e => new UserIndexViewModel
                    {
                        Id = e.Id,
                        Name = e.Name,
                        SurName1 = e.SurName1,
                        SurName2 = e.SurName2,
                        Address = e.Address,
                        ZipCode = e.ZipCode,
                        City = e.City,
                        Email = e.Email,
                        Password = e.Password,
                        Latitude = e.Latitude,
                        Longitude = e.Longitude
                    });

            JQueryDataTableResponse result = JQueryHelper.CreateJQueryDataTableResponse(model, request);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Método que muestra una tabla con todos los usuarios
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var model =
                userManager.GetAll()
                    .Select(e => new UserIndexViewModel
                    {
                        Id = e.Id,
                        Name = e.Name,
                        SurName1 = e.SurName1,
                        SurName2 = e.SurName2,
                        Address = e.Address,
                        ZipCode = e.ZipCode,
                        City = e.City,
                        Email = e.Email,
                        Password = e.Password,
                        Latitude = e.Latitude,
                        Longitude = e.Longitude
                    });

            return View(model);
        }
    }
}

Trademusic.Web/Controllers/AppController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using PagedList;
using System.Linq;
using System.Web.Mvc;
using Trademusic.CORE.Contracts;
using Trademusic.CORE.Domain.Classes;
using Trademusic.Web.Models.App;

namespace Trademusic.Web.Controllers
{
    public class AppController : Controller
    {
        private IInstrumentManager instrumentManager;
        private IFamilyManager familyManager;
        private IMessageManager messageManager;
        private IUserManager userManager;

        /// <summary>
        /// Constructor del controlador
        /// </summary>
        /// <param name="instrumentManager"></param>
        /// <param name="familyManager"></param>
        /// <param name="messageManager"></param>
        /// <param name="userManager"></param>
        public AppController(IInstrumentManager instrumentManager, IFamilyManager familyManager, IMessageManager messageManager, IUserManager userManager)
        {
            this.instrumentManager = instrumentManager;
            this.familyManager = familyManager;
            this.messageManager = messageManager;
            this.userManager = userManager;
        }

        /// <summary>
        /// Método para mostrar un listado de instrumentos por familia + paginación
        /// </summary>
        /// <param name="family"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Index(int family, int? page, string currentFilter, string searchString)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else { searchString = currentFilter; }
            ViewBag.CurrentFilter = searchString;

            var fam = familyManager.GetById(family);

            var model = instrumentManager.GetAllByFamily(family)
                    .Select(p => new InstrumentListViewModel {
                        Id = p.Id,
                        Name = p.Brand + " - " + p.Model,
                        Brand = p.Brand,
                        Price = p.Price,
                        Description = p.Description,
                        Family = fam.Name,
                        EngFamily = fam.EnglishName,
                        DateTime = p.DateTime,
                        User = p.User
                    }).ToList();

            ViewBag.family = family;
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            return View(model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Método para mostrar un listado de instrumentos por familia y marca + paginación
        /// </summary>
        /// <param name="family"></param>
        /// <param name="brand"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult IndexBrand(int family, string brand, int? page)
        {
            var fam = familyManager.GetById(family);

            var model = instrumentManager.GetAllByFamilyAndBrand(family, brand)
                    .Select(p => new InstrumentListViewModel
                    {
                        Id = p.Id,
                        Name = p.Brand + " - " + p.Model,
                        Brand = p.Brand,
                        Price = p.Price,
                        Description = p.Description,
                        Family = fam.Name,
                        EngFamily = fam.EnglishName,
                        DateTime = p.DateTime,
                        User = p.User
                    }).ToList();
            ViewBag.family = family;
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            return View("Index", model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Método para mostrar un listado de instrumentos por familia y ciudad + paginación
        /// </summary>
        /// <param name="family"></param>
        /// <param name="city"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult IndexCity(int family, string city, int? page)
        {
            var fam = familyManager.GetById(family);

            var model = instrumentManager.GetAllByFamilyAndCity(family, city)
                    .Select(p => new InstrumentListViewModel
                    {
                        Id = p.Id,
                        Name = p.Brand + " - " + p.Model,
                        Brand = p.Brand,
                        Price = p.Price,
                        Description = p.Description,
                        Family = fam.Name,
                        EngFamily = fam.EnglishName,
                        DateTime = p.DateTime,
                        User = p.User
                    }).ToList();

            ViewBag.family = family;
            ViewBag.city = city;
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            return View("Index", model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Método para mostrar un listado de instrumentos por familia y rango de precios + paginación
        /// </summary>
        /// <param name="family"></param>
        /// <param name="price1"></param>
        /// <param name="price2"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult IndexPriceRange(int family, int price1, int price2, int? page)
        {
            var fam = familyManager.GetById(family);

            var model = instrumentManager.GetAllByFamilyAndPriceRange(family, price1, price2)
                    .Select(p => new InstrumentListViewModel
                    {
                        Id = p.Id,
                        Name = p.Brand + " - " + p.Model,
                        Brand = p.Brand,
                        Price = p.Price,
                        Description = p.Description,
                        Family = fam.Name,
                        EngFamily = fam.EnglishName,
                        DateTime = p.DateTime,
                        User = p.User
                    }).ToList();
            ViewBag.family = family;
            ViewBag.price1 = price1;
            ViewBag.price2 = price2;
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            return View("Index", model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Método de autocompetado del cuadro de búsqueda
        /// </summary>
        /// <param name="term"></param>
        /// <returns></returns>
        //public JsonResult AutoCompleteInstrument(string term)
        //{
        //    var result = instrumentManager.GetAll().Where(i => i.Brand.ToLower().Contains(term.ToLower())).Select(i => i.Brand).Distinct();

        //    return Json(result, JsonRequestBehavior.AllowGet);
        //}

        public List<string> Search(string name)
        {
            var result = instrumentManager.GetAll().Where(i => i.Brand.StartsWith(name)).Select(i => i.Brand).ToList();

            return result;
        }

        /// <summary>
        /// Método para filtrar los instrumentos por familia
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListByFamily(int id)
        {
            var model = instrumentManager.GetAllByFamily(id)
                    .Select(p => new InstrumentListViewModel {
                        Id = p.Id,
                        Name = p.Brand + " - " + p.Model,
                        Brand = p.Brand,
                        Price = p.Price,
                        Description = p.Description,
                        Family = p.Family.Name,
                        EngFamily = p.Family.EnglishName,
                        DateTime = p.DateTime,
                        User = p.User
                    }).ToList();

            return PartialView("_ListPartial", model);
        }

        /// <summary>
        /// Método de llena las propiedades de la clase FamilyViewModel, de una manera recursiva
        /// </summary>
        /// <param name="families"></param>
        /// <param name="parentId"></param>
        /// <returns></returns>
        private List<FamilyMenuViewModel> GetElements(List<Family> families, int? parentId = null)
        {
            List<FamilyMenuViewModel> result = new List<FamilyMenuViewModel>();
            foreach (var family in families.Where(f => f.ParentId == parentId))
            {
                result.Add(new FamilyMenuViewModel {
                    ParentFamily = family,
                    SonFamily = GetElements(families, family.Id)
                });
            }
            return result;
        }

        /// <summary>
        /// Método que pinta todas las familias y subfamilias de un instrumento en una vista parcial para fitrar por ellas
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult FamilyMenu()
        {
            var families = familyManager.GetAll().ToList();
            FamilyMenuViewModel model = GetElements(families).FirstOrDefault();

            ViewData["userLanguage"] = CultureInfo.CurrentUICulture.Name.ToString();

            return PartialView("_FamilyMenu", model);
        }

        /// <summary>
        /// Método para filtrar los instrumentos por marca
        /// </summary>
        /// <param name="brand"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ListByBrand(string brand)
        {
            var model = instrumentManager.GetAllByBrand(brand)
                    .Select(p => new InstrumentListViewModel {
                        Id = p.Id,
                        Name = p.Brand + " - " + p.Model,
                        Brand = p.Brand,
                        Price = p.Price,

Trademusic.Web/Views/Home/Help.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = Resources.Language.HELP;
}

<section id="appIndex">
    <div class="container">
        <div class="row" id="seccionContenedorTexto">
            <h1>@Resources.Language.HELP</h1>

            <div class="body">
                <h2 class="profile-subsection-title">@Resources.Language.BASIC_INFO</h2>
                <h3>@Resources.Language.HOW_DO_I_REGISTER</h3>
                    <p>@Resources.Language.HOW_DO_I_REGISTER_AWNSER_1 <a href="/Account/Register">@Resources.Language.HERE</a>. @Resources.Language.HOW_DO_I_REGISTER_AWNSER_2</p>

                <h3>@Resources.Language.CANT_REMEMBER</h3>

                    <p>@Resources.Language.CANT_REMEMBER_AWNSER_1 <a href="/Account/ForgotPassword">@Resources.Language.HERE</a> @Resources.Language.CANT_REMEMBER_AWNSER_2</p>

                <h3>@Resources.Language.HOW_DO_I_ACCESS_TO_MY_SECTION</h3>

                    <p>@Resources.Language.HOW_DO_I_ACCESS_TO_MY_SECTION_AWNSER_1</p>
                    <p>@Resources.Language.HOW_DO_I_ACCESS_TO_MY_SECTION_AWNSER_2 <a href="/Account/Register">@Resources.Language.HERE</a></p>

                <h3>@Resources.Language.HOW_DO_I_CHANGE_MY_INFO</h3>

                    <p>@Resources.Language.HOW_DO_I_CHANGE_MY_INFO_AWNSER_1</p>
 
                <h3>@Resources.Language.HOW_DO_I_CHANGE_MY_PHOTO</h3>

                <p>@Resources.Language.HOW_DO_I_CHANGE_MY_PHOTO_AWNSER_1</p>

                <h3>@Resources.Language.BAN_USER</h3>

                    <p>@Resources.Language.BAN_USER_AWNSER_1</p>

                <h3>@Resources.Language.BAN_USER_WHAT_FOR</h3>

                    <p>@Resources.Language.BAN_USER_WHAT_FOR_AWNSER_1</p>
                    <p>@Resources.Language.BAN_USER_WHAT_FOR_AWNSER_2</p>
       
                <h3>@Resources.Language.DELETE_MY_ACCOUNT</h3>
          
                    <p>@Resources.Language.DELETE_MY_ACCOUNT_AWNSER_1</p>
                    <p><span class="bold">@Resources.Language.REMEMBER</span> @Resources.Language.DELETE_MY_ACCOUNT_AWNSER_2</p>
                    <p>@Resources.Language.DELETE_MY_ACCOUNT_AWNSER_3</p>
          
                <h2>@Resources.Language.TRADE</h2>
                <h3>@Resources.Language.UPLOAD_INSTRUMENT</h3>
            
                    <p>@Resources.Language.UPLOAD_INSTRUMENT_AWNSER_1</p>
                    <p>@Resources.Language.UPLOAD_INSTRUMENT_AWNSER_2</p>
        
                <h3>@Resources.Language.ANNOUNCEMENT_EXPIRES</h3>
              
                    <p>@Resources.Language.ANNOUNCEMENT_EXPIRES_AWNSER_1</p>
                    <p>@Resources.Language.ANNOUNCEMENT_EXPIRES_AWNSER_2</p>
            
                <h3>@Resources.Language.DELETE_INSTRUMENT</h3>
            
                    <p>@Resources.Language.DELETE_INSTRUMENT_AWNSER_1</p>
                    <p>@Resources.Language.DELETE_INSTRUMENT_AWNSER_2</p>
          
                <h3>@Resources.Language.TRADE_SHOP</h3>
             
                    <p>@Resources.Language.TRADE_SHOP_AWNSER_1</p>
           
                <h3>@Resources.Language.CANT_SEE_ANNOUNCEMENT</h3>
              
                    <p>@Resources.Language.CANT_SEE_ANNOUNCEMENT_AWNSER_1</p>
                    <p>@Resources.Language.CANT_SEE_ANNOUNCEMENT_AWNSER_2</p>                          
            </div>
        </div>
    </div>
</section>

Trademusic.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = Resources.Language.INDEX;
}

<header>
    <div class="header-content">
        <div class="header-content-inner">           
                <img src="~/Images/App/Logo trademusic_todo_naranja.png" />
            <hr>
            <h2>@Resources.Language.RESUME!</h2>
            <a href="#about" id="btnFindout" class="btn btn-primary btn-xl page-scroll">@Resources.Language.FIND_OUT_MORE</a>
        </div>
    </div>
</header>

<section  id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">@Resources.Language.PHRASE</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <img class="instrument-icon" src="~/Images/App/search-Icon.png" />
                    <h3>@Resources.Language.STEP1</h3>
                    <p class="text-muted">@Resources.Language.STEP1_EXPLANATION</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <img class="instrument-icon" src="~/Images/App/trade-Icon.png" />
                    <h3>@Resources.Language.STEP2</h3>
                    <p class="text-muted">@Resources.Language.STEP2_EXPLANATION</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <img class="instrument-icon" src="~/Images/App/money-Icon.png" />
                    <h3>@Resources.Language.STEP3</h3>
                    <p class="text-muted">@Resources.Language.STEP3_EXPLANATION</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="services" class="bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">@Resources.Language.CHOOSE_A_TYPE_OF_INSTRUMENT</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <a href="@Url.Action("Index", "App", new { family = 5 }, "")">
                        <img class="instrument-icon" src="~/Images/App/Guitar.png" />
                        <h3>@Resources.Language.GUITARS</h3>
                        <p class="text-muted">@Resources.Language.GUITAR_EXPLANATION.</p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <a href="@Url.Action("Index", "App", new { family = 9 },"")">
                        <img class="instrument-icon" src="~/Images/App/bass.png" />
                        <h3>@Resources.Language.BASSES</h3>
                        <p class="text-muted">@Resources.Language.BASS_EXPLANATION.</p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 text-center">
                <div class="service-box">
                    <a href="@Url.Action("Index", "App", new { family = 13 },"")">
                        <img class="instrument-icon" src="~/Images/App/drum.png" />
                        <h3>@Resources.Language.DRUMS</h3>
                        <p class="text-muted">@Resources.Language.DRUMS_EXPLANATION.</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<aside >
    <div class="container text-center">
        <div class="col-md-3">
            <img src="~/Images/App/Smartphones2.png" />
        </div>
        <div class="col-md-9">
            <label id="lblIndexApp">@Resources.Language.MOBILE_APP_EXPLANATION</label> 
            <a id="btnIndexApp" href="https://play.google.com/store/apps/details?id=com.daniel.trademusic2" class="btn btn-primary btn-xl sr-button">@Resources.Language.DOWNLOAD_HERE</a>
        </div>
    </div>
</aside>

Trademusic.Web/Views/Home/TradingRules.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = Resources.Language.TRADING_RULES;
}

<section id="appIndex">
    <div class="container">
        <div class="row" id="seccionContenedorTexto">
            <h1>@Resources.Language.TRADING_RULES</h1>
            <div>
                <h2>@Resources.Language.GENERAL_RULES</h2>
                <p>
                    @Resources.Language.GENERAL_RULES_1
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_2
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_3
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_4
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_5
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_6
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_7
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_8
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_9
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_10
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_11
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_12
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_13
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_14
                </p>
                <p>
                    @Resources.Language.GENERAL_RULES_15
                </p>
                <h2>@Resources.Language.BUYING_ADVICES</h2>
                <p>
                    @Resources.Language.BUYING_ADVICES_1
                </p>
                <p>
                    @Resources.Language.BUYING_ADVICES_2
                </p>
                <p>
                    @Resources.Language.BUYING_ADVICES_3
                </p>
                <p>
                    @Resources.Language.BUYING_ADVICES_4
                </p>
                <p>
                    @Resources.Language.BUYING_ADVICES_5
                </p>
                <p>
                    @Resources.Language.BUYING_ADVICES_6
                </p>
                <h2>@Resources.Language.SELLING_ADVICES</h2>
                <p>
                    @Resources.Language.SELLING_ADVICES_1
                </p>
                <p>
                    @Resources.Language.SELLING_ADVICES_2
                </p>
                <p>
                    @Resources.Language.SELLING_ADVICES_3
                </p>
                <h2>@Resources.Language.TREATMENT</h2>
                <p>
                    @Resources.Language.TREATMENT_1
                </p>
                <p>
                    @Resources.Language.TREATMENT_2
                </p>
                <p>
                    @Resources.Language.TREATMENT_3
                </p>
                <p>
                    @Resources.Language.TREATMENT_4
                </p>
            </div>
        </div>
    </div>
</section>

Trademusic.Web/Views/Home/_Menu.cshtml
@using System.Linq
@model Trademusic.Web.Models.App.FamilyMenuViewModel

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>
            <a href="#">
                @Resources.Language.INSTRUMENTS<i class="fa fa-angle-down"></i>
            </a>
            <ul class="sub-menu">
                <li>
                    @Html.ActionLink(Resources.Language.ELECTRIC_GUITARS, "Index", "App", new { family = 5 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.ACUSTIC_GUITARS, "Index", "App", new { family = 6 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.GUITAR_AMPS, "Index", "App", new { family = 7 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.GUITAR_EFECTS, "Index", "App", new { family = 8 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.ELECTRIC_BASSES, "Index", "App", new { family = 9 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.ACUSTIC_BASSES, "Index", "App", new { family = 10 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.BASS_AMPS, "Index", "App", new { family = 11 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.BASS_EFECTS, "Index", "App", new { family = 12 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.DRUMS, "Index", "App", new { family = 13 }, new { @class = "" })
                </li>
                <li>
                    @Html.ActionLink(Resources.Language.DRUM_PARTS, "Index", "App", new { family = 14 }, new { @class = "" })
                </li>
            </ul>
        </li>
        <li>
            @Html.ActionLink(Resources.Language.MAP, "Map", "Home", "", new { @class = "" })
        </li>
        <li>
            <a href="">@Resources.Language.LANGUAGE<i class="fa fa-angle-down"></i></a>
            <ul class="sub-menu">
                <li>@Html.ActionLink(Resources.Language.SPANISH, "Change", "Home", new { langAbrvtion = "es" }, null)</li>
                <li>@Html.ActionLink(Resources.Language.ENGLISH, "Change", "Home", new { langAbrvtion = "en" }, null))</li>
            </ul>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            <li>@Html.ActionLink(Resources.Language.USERS_SECTION, "Main", "UserSection", "", new { @class = "" })</li>
        }
        <li>
            @if (User.IsInRole("Admin"))
            {
                <a href="">Admin<i class="fa fa-angle-down"></i></a>
                <ul class="sub-menu">
                    <li>@Html.ActionLink(Resources.Language.INSTRUMENTS, "Index", "Instrument", new { area = "Admin" }, new { @class = "" })</li>
                    <li>@Html.ActionLink(Resources.Language.FAMILIES, "Index", "Family", new { area = "Admin" }, new { @class = "" })</li>
                    <li>@Html.ActionLink(Resources.Language.MESSAGES, "Index", "Message", new { area = "Admin" }, new { @class = "" })</li>
                    <li>@Html.ActionLink(Resources.Language.USERS, "Index", "User", new { area = "Admin" }, new { @class = "" })</li>
                </ul>
            }
        </li>
    </ul>

    @Html.Partial("_LoginPartial")
</div>

@section Scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {

            //Método que pinta el listado de instrumentos con la categoría de instrumentos seleccionada desde la barra de menú
            $(".families").click(function () {
                var id = $(this).data("id");
                $.ajax({
                    url: '@Url.Action("ListByFamily", "App")',
                    type: 'GET',
                    data: { id: id }
                }).done(function (response) {
                    @Url.Action("Index", "App")
                    $("#dvList").html(response);
                });
            });
        });
    </script>
}